; ------------------ addition
AssertEqual (+) 0
AssertEqual (+ 2 2) 4
AssertEqual (+ 2 2 2 2) 8

; ------------------ subtraction
AssertEqual (- 1) -1
AssertEqual (- 10 2) 8
AssertEqual (- 10 2 2 2) 4

; ------------------ multiplication
AssertEqual (*) 1
AssertEqual (* 2) 2
AssertEqual (* 2 2) 4
AssertEqual (* 2 2 2 2) 16

; ------------------ division
AssertEqual (/ 1) 1
AssertEqual (/ 2) 0.5
AssertEqual (/ 4 2) 2
AssertEqual (/ 8 2 2) 2

; ------------------ modulo
AssertEqual (% 5) 5
AssertEqual (% 5 5) 0
AssertEqual (% 25 10 2) 1

; ------------------ comparison
AssertTrue (== 5 5)
AssertTrue (<= 4 5)
AssertTrue (<= 5 5)
AssertTrue (>= 5 4)
AssertTrue (>= 5 5)
AssertTrue (< 4 5)
AssertTrue (> 5 4)

; ------------------ increment
AssertEqual (++ 5) 6

; ------------------ decrement
AssertEqual (-- 5) 4

; ------------------ add assignment
local x 10
+= x 3
AssertEqual x 13
= x 10
+= x 1 1 1 1 1
AssertEqual x 15

; ------------------ sub assignment
= x 10
-= x 3
AssertEqual x 7
= x 10
-= x 1 1 1 1 1
AssertEqual x 5

; ------------------ mult assignment
= x 10
*= x 3
AssertEqual x 30
= x 10
*= x 2 2 2
AssertEqual x 80

; ------------------ div assignment
= x 10
/= x 2
AssertEqual x 5
= x 24
/= x 2 2
AssertEqual x 6

; ------------------ modulo assignment
= x 10
%= x 4
AssertEqual x 2
= x 25
%= x 10 2
AssertEqual x 1